# ~/.config/kitty/kitty.conf

# =========================
# FONT
# =========================

font_family      Cascadia Mono PL
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 10

adjust_column_width 1

disable_ligatures never

# =========================
# WINDOW
# =========================

background_opacity 0.50
confirm_os_window_close 0

dynamic_background_opacity yes

window_padding_width 20
hide_window_decorations yes

wayland_titlebar_color background

# blur wayland
background_blur 10

# =========================
# CURSOR
# =========================

cursor_shape beam
cursor_beam_thickness 1.5

cursor_blink_interval 0.45
cursor_stop_blinking_after 15

# =========================
# SCROLL
# =========================

scrollback_lines 10000
wheel_scroll_multiplier 5.0

# =========================
# TAB BAR
# =========================

tab_bar_edge top
tab_bar_style powerline

tab_powerline_style slanted

active_tab_foreground   #16161D
active_tab_background   #89b4fa

inactive_tab_foreground #b6b09e
inactive_tab_background #1d1d27

tab_separator " ┇ "

# =========================
# COLORS
# =========================

foreground              #d5c89a
background              #16161D

selection_foreground    #16161D
selection_background    #89b4fa

url_color               #89b4fa

active_border_color     #89b4fa
inactive_border_color   #1d1d27

active_tab_font_style bold

# black
color0  #1d1d27
color8  #3b4252

# red
color1  #e67e80
color9  #ef9a9a

# green
color2  #a7c080
color10 #b5cea8

# yellow
color3  #d5c89a
color11 #ebdbb2

# blue
color4  #89b4fa
color12 #a5c8ff

# magenta
color5  #c6a0f6
color13 #d7bdf8

# cyan
color6  #8bd5ca
color14 #9fe3d9

# white
color7  #d8dee9
color15 #eceff4

# =========================
# MISC
# =========================

enable_audio_bell no
visual_bell_duration 0.0

shell_integration enabled

copy_on_select yes

linux_display_server wayland