# =========================
# HYPRLAND MAIN CONFIG
# =========================

# =========
# THEME
# =========
source = ~/.config/hypr/themes/colors.conf
source = ~/.config/hypr/themes/decoration.conf
source = ~/.config/hypr/themes/animation.conf

# =========
# SYSTEM
# =========
source = ~/.config/hypr/configs/environment.conf
source = ~/.config/hypr/configs/monitor.conf
source = ~/.config/hypr/configs/input.conf

# =========
# WINDOW / WORKSPACE
# =========
source = ~/.config/hypr/configs/rules.conf
source = ~/.config/hypr/configs/workspace.conf

# =========
# AUTOSTART
# =========
source = ~/.config/hypr/configs/autostart.conf

# =========
# KEYBINDS
# =========
source = ~/.config/hypr/configs/keybinds.conf