animations {
    enabled = yes

    # Bezier Curve
    bezier = Cubic, 0.22,0.61,0.36,1
    bezier = Quart, 0.17,0.84,0.44,1
    bezier = Quint, 0.23,1,0.32,1
    bezier = Expo, 0.19,1,0.22,1
    bezier = Cubic, 0.22,0.61,0.36,1
    # WINDOWS
    animation = windows, 1, 5, Expo, popin 87%
    animation = windowsIn, 1, 5, Quart, popin 87%
    animation = windowsOut, 1, 4, Quart, popin 87%

    # BORDER
    animation = border, 1, 8, default

    # FADE
    animation = fade, 1, 5, Quint
    animation = fadeDim, 1, 5, Quint

    # WORKSPACE
    animation = workspaces, 1, 6, Expo

    # SPECIAL WORKSPACE
    animation = specialWorkspace, 1, 5, Quint, slidevert
}