animations {
    enabled = yes

    # Bezier Curve
    bezier = smoothOut, 0.36, 0, 0.66, -0.56
    bezier = smoothIn, 0.25, 1, 0.5, 1
    bezier = smoothMove, 0.05, 0.9, 0.1, 1.05
    bezier = smoothFade, 0.3, 0, 0.8, 0.15

    # WINDOWS
    animation = windows, 1, 5, smoothMove
    animation = windowsIn, 1, 5, smoothIn, popin 87%
    animation = windowsOut, 1, 4, smoothFade, popin 87%

    # BORDER
    animation = border, 1, 8, default

    # FADE
    animation = fade, 1, 5, smoothFade
    animation = fadeDim, 1, 5, smoothFade

    # WORKSPACE
    animation = workspaces, 1, 6, smoothMove

    # SPECIAL WORKSPACE
    animation = specialWorkspace, 1, 5, smoothMove, slidevert
}