# =========================
# GENERAL WINDOW LOOK
# =========================

general {
    gaps_in = 5
    gaps_out = 10

    border_size = 2

    col.active_border = rgba(89b4faff)
    col.inactive_border = rgba(585b70aa)

    resize_on_border = true
    layout = dwindle
}

# =========================
# WINDOW DECORATION
# =========================

decoration {
    rounding = 12

    active_opacity = 1.0
    inactive_opacity = 0.95
    fullscreen_opacity = 1.0

    shadow {
        enabled = true
        range = 20
        render_power = 3
    }

    blur {
        enabled = true
        size = 6
        passes = 3

        vibrancy = 0.2
    }
}