# =========================
# AUTOSTART
# =========================

# Status bar
exec-once = waybar

# Notification daemon
exec-once = swaync

# Wallpaper daemon
exec-once = hyprpaper

# Network manager tray
exec-once = nm-applet

# Bluetooth tray
exec-once = blueman-applet

# Clipboard manager
exec-once = ~/.config/hypr/scripts/clipboard-watch.sh

# Polkit authentication
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Idle daemon
exec-once = hypridle

# Discord (optional)
# exec-once = discord

# Browser (optional)
# exec-once = firefox

exec-once = hyprpanel
