# =========================
# CURSOR
# =========================

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# =========================
# WAYLAND SUPPORT
# =========================

env = QT_QPA_PLATFORM,wayland
env = GDK_BACKEND,wayland,x11
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland

# =========================
# ELECTRON APPS
# =========================

env = ELECTRON_OZONE_PLATFORM_HINT,auto

# =========================
# THEME
# =========================

env = GTK_THEME,Catppuccin-Mocha-Standard-Blue-Dark

# =========================
# MOZILLA
# =========================

env = MOZ_ENABLE_WAYLAND,1

# =========================
# NVIDIA (optional)
# =========================

# env = LIBVA_DRIVER_NAME,nvidia
# env = __GLX_VENDOR_LIBRARY_NAME,nvidia