# =========================
# INPUT CONFIG
# =========================

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0.5

    touchpad {
        natural_scroll = true
        disable_while_typing = true
        tap-to-click = true
        scroll_factor = 1.0
    }
}

# =========================
# MOUSE
# =========================

device {
    name = epic-mouse-v1

    sensitivity = -0.3
}