windowrule {
    name = pavucontrol-float
    match:class = ^(pavucontrol)$

    float = true
    center = true
}

windowrule {
    name = nm-float
    match:class = ^(nm-connection-editor)$

    float = true
}

windowrule {
    name = blueman-float
    match:class = ^(blueman-manager)$

    float = true
}

windowrule {
    name = calc-float
    match:class = ^(org.gnome.Calculator)$

    float = true
    center = true
}

windowrule {
    name = firefox-workspace
    match:class = ^(firefox)$

    workspace = 1
}

windowrule {
    name = code-workspace
    match:class = ^(code)$

    workspace = 2
}