windowrule = match:class ^(pavucontrol)$, float on
windowrule = match:class ^(pavucontrol)$, center on

windowrule = match:class ^(nm-connection-editor)$, float on
windowrule = match:class ^(nm-connection-editor)$, center on

windowrule = match:class ^(blueman-manager)$, float on
windowrule = match:class ^(blueman-manager)$, center on

windowrule = match:class ^(org.gnome.Calculator)$, float on
windowrule = match:class ^(org.gnome.Calculator)$, center on

windowrule = match:class ^(firefox)$,
windowrule = match:class ^(code|code-oss)$,

windowrule = match:class ^(code|code-oss)$, opacity 0.90, rounding 5

windowrule = match:class ^(Spotify)$, opacity 0.80
windowrule = match:class ^(Spotify)$, rounding 5